services:
  mongo:
    image: mongo:8
    ports:
      - "59593:27017"
    volumes:
      - mongo-data:/data/db

  app:
    build: .
    ports:
      - "${PORT:-3000}:3000"
    env_file:
      - .env.develop
    environment:
      - MONGODB_CONNSTRING=mongodb://mongo:27017/template-backend
    depends_on:
      - mongo

volumes:
  mongo-data:
